In [73]:
import pandas as pd
s=pd.Series([1,2,3,4,5,6])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [74]:
import numpy as np
date=pd.date_range('20180630',periods=6)
print(date)
df=pd.DataFrame(np.random.randn(6,4),index=date,columns=list('ABCD'))
print(df)
print(df.index)#prints index
print(df.columns)#prints columns
print(df.values)#prints values
print(df.describe())#describe summury of table
print(df.T)#prints transpose of dataframe
print(df.sort_index(axis=1,ascending=False))#sorts columnwise decreasing
print(df.sort_values(by='B'))#sorts values by column B

DatetimeIndex(['2018-06-30', '2018-07-01', '2018-07-02', '2018-07-03',
               '2018-07-04', '2018-07-05'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2018-06-30  0.781247  0.803260 -0.200712 -1.848148
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586
2018-07-02 -0.913158 -0.125391  0.022065  1.840978
2018-07-03  0.345147 -0.086069  1.465351  0.690981
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331
2018-07-05 -0.123537 -0.576258  0.894514 -0.928090
DatetimeIndex(['2018-06-30', '2018-07-01', '2018-07-02', '2018-07-03',
               '2018-07-04', '2018-07-05'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0.78124722  0.80325973 -0.20071245 -1.84814768]
 [-0.28308098 -0.67024271 -1.40412298 -0.57258638]
 [-0.91315772 -0.12539125  0.02206547  1.84097841]
 [ 0.3451467  -0.08606878  1.46535121  0.69098075]
 [-0.2194032  -0.94693961 -0.63698464  0.63333099]
 [-0.12353722 -0.5

In [75]:
df2 = pd.DataFrame({ 'A' : 1.,
                             'B' : pd.Timestamp('20130102'),
                             'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                             'D' : np.array([3] * 4,dtype='int32'),
                             'E' : pd.Categorical(["test","train","test","train"]),
                             'F' : 'foo' })
print(df2)
print(df2.tail(1))
print(df2.head(1))

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
     A          B    C  D      E    F
3  1.0 2013-01-02  1.0  3  train  foo
     A          B    C  D     E    F
0  1.0 2013-01-02  1.0  3  test  foo


In [76]:
print(df)
print(df['A'])
print(df[0:3])
print(df['20180703':'20180705'])

                   A         B         C         D
2018-06-30  0.781247  0.803260 -0.200712 -1.848148
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586
2018-07-02 -0.913158 -0.125391  0.022065  1.840978
2018-07-03  0.345147 -0.086069  1.465351  0.690981
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331
2018-07-05 -0.123537 -0.576258  0.894514 -0.928090
2018-06-30    0.781247
2018-07-01   -0.283081
2018-07-02   -0.913158
2018-07-03    0.345147
2018-07-04   -0.219403
2018-07-05   -0.123537
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2018-06-30  0.781247  0.803260 -0.200712 -1.848148
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586
2018-07-02 -0.913158 -0.125391  0.022065  1.840978
                   A         B         C         D
2018-07-03  0.345147 -0.086069  1.465351  0.690981
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331
2018-07-05 -0.123537 -0.576258  0.894514 -0.928090


In [77]:
print(df.loc[date[0]])#viewing using label
print(df.loc[:,['A','B']])
print(df.loc['20180702':'20180705',['C','D']])
print(df.loc[date[0],'A'])
print(df.iloc[[1,2,4],[0,2]])#selection by position as in numpy

A    0.781247
B    0.803260
C   -0.200712
D   -1.848148
Name: 2018-06-30 00:00:00, dtype: float64
                   A         B
2018-06-30  0.781247  0.803260
2018-07-01 -0.283081 -0.670243
2018-07-02 -0.913158 -0.125391
2018-07-03  0.345147 -0.086069
2018-07-04 -0.219403 -0.946940
2018-07-05 -0.123537 -0.576258
                   C         D
2018-07-02  0.022065  1.840978
2018-07-03  1.465351  0.690981
2018-07-04 -0.636985  0.633331
2018-07-05  0.894514 -0.928090
0.7812472170948107
                   A         C
2018-07-01 -0.283081 -1.404123
2018-07-02 -0.913158  0.022065
2018-07-04 -0.219403 -0.636985


In [78]:
print(df)
print(df[df.A>0])
print(df[df>0])
df2=df.copy()
df2['E']=['one','one','two','three','three','one']
print(df2)
print(pd.concat([df, df2], join='inner', axis=1))#joins horizontally

                   A         B         C         D
2018-06-30  0.781247  0.803260 -0.200712 -1.848148
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586
2018-07-02 -0.913158 -0.125391  0.022065  1.840978
2018-07-03  0.345147 -0.086069  1.465351  0.690981
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331
2018-07-05 -0.123537 -0.576258  0.894514 -0.928090
                   A         B         C         D
2018-06-30  0.781247  0.803260 -0.200712 -1.848148
2018-07-03  0.345147 -0.086069  1.465351  0.690981
                   A        B         C         D
2018-06-30  0.781247  0.80326       NaN       NaN
2018-07-01       NaN      NaN       NaN       NaN
2018-07-02       NaN      NaN  0.022065  1.840978
2018-07-03  0.345147      NaN  1.465351  0.690981
2018-07-04       NaN      NaN       NaN  0.633331
2018-07-05       NaN      NaN  0.894514       NaN
                   A         B         C         D      E
2018-06-30  0.781247  0.803260 -0.200712 -1.848148    one
2018-07-01 -0.283081 -0.

In [79]:
print(df2)
print(df2['B'][df2['E']=='two'])
print(df2[(df2['E']=='two')|(df2['E']=='three')])
df2.loc[df2['A'] > 0, 'B'] *= 2#same as UPDATE tips SET tip = tip*2 WHERE tip < 2; of SQL command
print(df2)

                   A         B         C         D      E
2018-06-30  0.781247  0.803260 -0.200712 -1.848148    one
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586    one
2018-07-02 -0.913158 -0.125391  0.022065  1.840978    two
2018-07-03  0.345147 -0.086069  1.465351  0.690981  three
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331  three
2018-07-05 -0.123537 -0.576258  0.894514 -0.928090    one
2018-07-02   -0.125391
Freq: D, Name: B, dtype: float64
                   A         B         C         D      E
2018-07-02 -0.913158 -0.125391  0.022065  1.840978    two
2018-07-03  0.345147 -0.086069  1.465351  0.690981  three
2018-07-04 -0.219403 -0.946940 -0.636985  0.633331  three
                   A         B         C         D      E
2018-06-30  0.781247  1.606519 -0.200712 -1.848148    one
2018-07-01 -0.283081 -0.670243 -1.404123 -0.572586    one
2018-07-02 -0.913158 -0.125391  0.022065  1.840978    two
2018-07-03  0.345147 -0.172138  1.465351  0.690981  three
2018-07-04 -0.21

In [80]:
url = 'https://raw.github.com/pandas-dev/pandas/master/pandas/tests/data/tips.csv'
df3 = pd.read_csv(url)
frame = pd.DataFrame({'col1': ['A', 'B', np.NaN, 'C', 'D'],'col2': ['F', np.NaN, 'G', 'H', 'I']})
print(frame.shape)#gives shape
print(frame[frame['col2'].isna()])#gives null values
print(frame[frame['col1'].notna()])#gives not null values
print(df3.groupby('sex').size())
print(df3.groupby('day').agg({'tip':np.mean,'day':np.size}))#Multiple functions can also be applied at once. For instance, say we’d like to see how tip amount differs by day of the week - agg() allows you to pass a dictionary to your grouped DataFrame, indicating which functions to apply to specific columns.
print(df3.groupby(['day','smoker']).agg({'tip':[np.size,np.mean]}))
df3.loc[df3['tip'] <2, 'tip'] *= 2#same as UPDATE tips SET tip = tip*2 WHERE tip < 2; of SQL command

(5, 2)
  col1 col2
1    B  NaN
  col1 col2
0    A    F
1    B  NaN
3    C    H
4    D    I
sex
Female     87
Male      157
dtype: int64
           tip  day
day                
Fri   2.734737   19
Sat   2.993103   87
Sun   3.255132   76
Thur  2.771452   62
              tip          
             size      mean
day  smoker                
Fri  No       4.0  2.812500
     Yes     15.0  2.714000
Sat  No      45.0  3.102889
     Yes     42.0  2.875476
Sun  No      57.0  3.167895
     Yes     19.0  3.516842
Thur No      45.0  2.673778
     Yes     17.0  3.030000


In [81]:
df4 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],'value': np.random.randn(4)})
df5 = pd.DataFrame({'key': ['B', 'D', 'D', 'E'],'value': np.random.randn(4)})
print(pd.merge(df4, df5, on='key'))#merges to dataframes
print(pd.merge(df4, df5, on='key', how='left'))#show all records from df1
print(pd.merge(df4, df5, on='key', how='right'))#show all records from df2
print(pd.merge(df4, df5, on='key', how='outer'))#show all records from both frames

  key   value_x   value_y
0   B -1.198717  2.158674
1   D -1.086186 -2.080906
2   D -1.086186 -0.114583
  key   value_x   value_y
0   A  0.656624       NaN
1   B -1.198717  2.158674
2   C  1.752955       NaN
3   D -1.086186 -2.080906
4   D -1.086186 -0.114583
  key   value_x   value_y
0   B -1.198717  2.158674
1   D -1.086186 -2.080906
2   D -1.086186 -0.114583
3   E       NaN  0.887811
  key   value_x   value_y
0   A  0.656624       NaN
1   B -1.198717  2.158674
2   C  1.752955       NaN
3   D -1.086186 -2.080906
4   D -1.086186 -0.114583
5   E       NaN  0.887811


In [82]:
df6 = pd.DataFrame({'city': ['Chicago', 'San Francisco', 'New York City'],'rank': range(1, 4)})
df7 = pd.DataFrame({'city': ['Chicago', 'Boston', 'Los Angeles'],'rank': [1, 4, 5]})
print(pd.concat([df6,df7]))#gives union
print(pd.concat([df6, df7]).drop_duplicates())#remove duplicates

            city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
0        Chicago     1
1         Boston     4
2    Los Angeles     5
            city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
1         Boston     4
2    Los Angeles     5


In [114]:
#creating on df
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df8 = pd.DataFrame(weather_data)
#reading existing excel file
df8 = pd.read_csv("weather_data.csv")
print(df8)
print(df8[['day','temperature']])
print(df8['temperature'].max())
print(df8['temperature'].std())
df8.set_index('day')#this only shows df wrt day as index
df8.set_index('day', inplace=True)#this modifies df wrt day as index
print(df8.loc['1/4/2017'])
df8.set_index('event', inplace=True)
print(df8.loc['Snow'])
df8.reset_index(inplace=True)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny
        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31
35
3.8297084310253524
temperature      24
windspeed         7
event          Snow
Name: 1/4/2017, dtype: object
       temperature  windspeed
event                        
Snow            28          2
Snow            24          7


In [118]:
df9=pd.read_csv('stock_data.csv',skiprows=1)#skips 1st row
df9 = pd.read_csv("stock_data.csv", header=None, names = ["ticker","eps","revenue","people"])
df9

ticker      eps revenue         people
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata